version: '3.7'

services:
  gateway:
    build:
      context: ./gateway
    ports:
      - "3000:3000"
    environment:
      - USER_SERVICE_URI=http://ms-user:3001
    depends_on:
      - ms-user
    networks:
      - blackcat-network

  ms-user:
    build:
      context: ./ms-user
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
      - JWT_SECRET=your_secret_key
    depends_on:
      - mongo
    networks:
      - blackcat-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - blackcat-network

networks:
  blackcat-network:
    driver: bridge
